# AML training pipeline

trigger:
- master

variables:
- group: AML-Shareshift-Forecasting

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- bash: conda env create --quiet --file training_env.yml
  displayName: Create Anaconda environment

- bash: source activate amlenv
  displayName: Activate Conda environment

- task: AzureCLI@1
  inputs:
    azureSubscription: 'Shareshift'
    scriptLocation: 'scriptPath'
    scriptPath: '02_submit_training.py'
    arguments: '--datastore_folder $DATASTORE_FOLDER --file_prefix $FILE_PREFIX --granularity $GRANULARITY --horizon $HORIZON'
