# AML training pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- bash: conda env create --quiet --file training_env.yml
  displayName: Create Anaconda environment

- bash: source activate amlenv
  displayName: Activate Conda environment

