# AML training pipeline

trigger:
- master

variables:
- group: AML Shareshift Forecasting

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    addToPath: true
    architecture: 'x64'

- bash: |
   python -m pip install --upgrade azureml-sdk[automl]
  
  displayName: Install Azure ML SDK

- task: AzureCLI@1
  inputs:
    azureSubscription: 'Shareshift'
    scriptLocation: inlineScript
    inlineScript: |
     # just need az cli credential for the Azure ML python code later on.
     python 02_submit_training.py

    arguments: '--datastore_folder $DATASTORE_FOLDER --file_prefix $FILE_PREFIX --granularity $GRANULARITY --horizon $HORIZON'
